export const CURATED_ENTRIES = [
  // ---- Standards: SEPs ----
  { id: "sep-6", type: "standard", title: "SEP-6 — Deposit & Withdrawal", description: "Anchor-hosted deposit/withdraw for any asset via the Transfer Server.", keywords: ["sep6", "anchor", "deposit", "withdraw", "kyc", "transfer-server"], source: "https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md" },
  { id: "sep-10", type: "standard", title: "SEP-10 — Web Authentication", description: "Stellar-based auth flow proving wallet ownership to web services.", keywords: ["sep10", "auth", "challenge", "web", "login", "jwt"], source: "https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md" },
  { id: "sep-12", type: "standard", title: "SEP-12 — KYC API", description: "Anchor KYC data collection endpoints, complementing SEP-6 and SEP-24.", keywords: ["sep12", "kyc", "aml", "verification", "anchor"], source: "https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0012.md" },
  { id: "sep-24", type: "standard", title: "SEP-24 — Interactive Hosted Deposit/Withdrawal", description: "Interactive anchor flows rendered in a web app for user consent.", keywords: ["sep24", "interactive", "anchor", "deposit", "withdraw", "hosted"], source: "https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md" },
  { id: "sep-38", type: "standard", title: "SEP-38 — Quote Server", description: "Off-chain FX quotes between assets and currencies for on/off ramps.", keywords: ["sep38", "quote", "fx", "currency", "anchor"], source: "https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md" },
  { id: "sep-41", type: "standard", title: "SEP-41 — Token Interface for Soroban", description: "Standard token interface mapping between classic assets and Soroban contracts (SAC).", keywords: ["sep41", "token", "soroban", "sac", "interface"], source: "https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0041.md" },
  { id: "sep-42", type: "standard", title: "SEP-42 — Build-Ahead / Post-Payment Transactions", description: "Fee-bumping and deferred signatures for zero-fee onboarding UX.", keywords: ["sep42", "fee-bump", "deferred", "onboarding", "sponsored"], source: "https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0042.md" },

  // ---- Standards: CAPs ----
  { id: "cap-21", type: "standard", title: "CAP-21 — Pre-Auth Transactions", description: "Signed-but-unsubmitted transactions enabling deferred settlement.", keywords: ["cap21", "preauth", "pre-authorized", "transaction", "settlement"], source: "https://github.com/stellar/stellar-protocol/blob/master/core/cap-0021.md" },
  { id: "cap-46", type: "standard", title: "CAP-46 — Smart Contracts (Soroban)", description: "WASM smart contracts on Stellar with a Rust SDK and host functions.", keywords: ["cap46", "soroban", "smart-contracts", "wasm", "rust"], source: "https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046.md" },
  { id: "cap-59", type: "standard", title: "CAP-59 — BLS12-381 Host Functions", description: "Elliptic curve ops enabling on-chain Groth16 zk-proof verification.", keywords: ["cap59", "bls12-381", "groth16", "zk", "zero-knowledge", "cryptography"], source: "https://github.com/stellar/stellar-protocol/blob/master/core/cap-0059.md" },
  { id: "cap-74", type: "standard", title: "CAP-74 — State Expiration", description: "Persistent contract storage with TTL-based rent and resurrection.", keywords: ["cap74", "ttl", "storage", "expiration", "rent"], source: "https://github.com/stellar/stellar-protocol/blob/master/core/cap-0074.md" },
  { id: "cap-75", type: "standard", title: "CAP-75 — Versioning / Contract Upgrade", description: "Interface-versioned contract upgrades preserving storage.", keywords: ["cap75", "upgrade", "versioning", "migration", "deployment"], source: "https://github.com/stellar/stellar-protocol/blob/master/core/cap-0075.md" },

  // ---- Ecosystem ----
  { id: "usdc", type: "ecosystem", title: "USDC on Stellar", description: "Circle's USDC native on Stellar — the default settlement asset for agentic payments.", keywords: ["usdc", "circle", "stablecoin", "settlement", "payments"], source: "https://www.circle.com/usdc-on-stellar" },
  { id: "x402-org", type: "ecosystem", title: "x402 — HTTP 402 Paid APIs", description: "Protocol for machine-payable APIs via HTTP 402 + crypto settlement.", keywords: ["x402", "402", "paid-api", "paywall", "agentic-payments"], source: "https://x402.org" },
  { id: "mpp", type: "ecosystem", title: "MPP — Machine Payments Protocol", description: "Charge/Channel modes for agent-to-agent and machine-to-machine payments.", keywords: ["mpp", "machine-payments", "charge", "channel", "agentic-payments"], source: "https://github.com/x402/mpp" },
  { id: "agentic-kit", type: "ecosystem", title: "Stellar Agentic Kit", description: "React hooks + data layer (useStellarData, useContract, useStellarWallet) for dApp UIs.", keywords: ["agentic-kit", "react", "hooks", "usestellardata", "dapp"], source: "https://github.com/stellar/agentic-kit" },
  { id: "stellar-raven", type: "ecosystem", title: "Stellar Raven", description: "SDF experimental remote MCP server: Stellar docs + ecosystem context for agents.", keywords: ["raven", "mcp", "docs", "catalog", "ecosystem"], source: "https://raven.stellar.org" },
  { id: "freighter", type: "ecosystem", title: "Freighter Wallet", description: "Browser wallet for Stellar + Soroban with a JS API.", keywords: ["freighter", "wallet", "browser", "soroban"], source: "https://www.freighter.app" },
  { id: "wallets-kit", type: "ecosystem", title: "Stellar Wallets Kit", description: "Multi-wallet connector kit (@creit.tech/stellar-wallets-kit) for dApps.", keywords: ["wallets-kit", "wallet", "connect", "multichain", "dapp"], source: "https://github.com/Creit-Tech/Soroban-React-Wallet" },
  { id: "soroban-rpc", type: "ecosystem", title: "Soroban RPC", description: "JSON-RPC for Soroban contract execution, simulation and events.", keywords: ["rpc", "soroban", "json-rpc", "simulate", "events"], source: "https://soroban.stellar.org" },

  // ---- Community intel ----
  { id: "scf-program", type: "intel", title: "Stellar Community Fund (SCF)", description: "Grants up to $150k XLM for builders — Open / Integration / RFP tracks, milestone tranches.", keywords: ["scf", "grant", "funding", "community-fund", "xlm", "tranche"], source: "https://communityfund.stellar.org" },
  { id: "scf-handbook", type: "intel", title: "SCF Program Handbook", description: "Quarterly program rules: tracks, tranche %s, deadlines, budget DOs/DON'Ts.", keywords: ["scf", "handbook", "tranche", "rules", "deadline"], source: "https://github.com/stellar/scf-handbook" },
  { id: "instaward", type: "intel", title: "Ambassador Instaward Program", description: "Fast-track SDF awards for ambassador chapter projects, 30-day sprints.", keywords: ["instaward", "ambassador", "sdf", "award", "sprint"], source: "https://communityfund.stellar.org" },
  { id: "stellar-governance", type: "intel", title: "Stellar Governance", description: "SCF governance, protocol votes and community decision-making.", keywords: ["governance", "vote", "scf", "protocol", "community"], source: "https://stellar.org/foundation" },

  // ---- Playbooks ----
  { id: "playbook-x402-api", type: "playbook", title: "Playbook — Ship a paid API with x402", description: "Charge per-request with USDC: 402 challenge, wallet payment, 200 response.", keywords: ["x402", "playbook", "paid-api", "402", "usdc", "paywall"], source: "skills/agentic-payments", steps: ["Install @x402/express + @x402/stellar in the backend", "Protect a route: return 402 with an x402 challenge on first hit", "Add the payment route that settles the invoice and returns the resource", "Fund the receiver wallet with USDC testnet to accept payments", "Verify with curl: expect 402 then 200 after paying the challenge"] },
  { id: "playbook-mpp-charge", type: "playbook", title: "Playbook — MPP Charge-mode payments", description: "One-off machine payments with per-charge invoices.", keywords: ["mpp", "charge", "playbook", "invoice", "machine-payments"], source: "skills/agentic-payments", steps: ["Add @stellar/mpp + mppx to the backend", "Configure a Charge wallet with the USDC address", "Generate a charge (invoice) per request", "Settle the charge on-chain, verify with getCharge"] },
  { id: "playbook-token", type: "playbook", title: "Playbook — Issue a token & bridge to SAC", description: "Classic asset issuance, trustlines, authorization flags, SAC wrapper.", keywords: ["token", "issuance", "trustline", "sac", "playbook", "asset"], source: "skills/assets", steps: ["Create the issuing account and configure authorization flags", "Issue the asset, set up distribution accounts", "Add a trustline from the holder to the issuer", "Deploy the Stellar Asset Contract wrapper for Soroban interop"] },
  { id: "playbook-vault", type: "playbook", title: "Playbook — Trustless milestone escrow (Forge Vault)", description: "Lock funds on-chain; recipient claims by proof, arbiter mediates, deadline recovery.", keywords: ["vault", "escrow", "milestone", "playbook", "soroban", "trustless"], source: "templates/contracts/vault", steps: ["Initialize the vault with depositor, recipient, arbiter and milestone amounts", "Depositor funds the vault to the committed total", "Recipient claims each milestone with its release-key proof", "Arbiter can force-release or refund unclaimed funds", "After the deadline the depositor can recover everything unclaimed"] },
  { id: "playbook-deploy", type: "playbook", title: "Playbook — Deploy a Soroban contract", description: "Build WASM, cargo-test gate, deploy to testnet, record evidence.", keywords: ["deploy", "soroban", "wasm", "testnet", "playbook", "stellar-cli"], source: "scripts/deploy-contract.sh", steps: ["Install stellar CLI 27+ and the wasm32v1-none target", "cargo build --release --target wasm32v1-none in the contract dir", "Run cargo test to gate the deploy", "Fund a deployer key via friendbot on testnet", "stellar contract deploy --wasm <file> --source-account <key> --network testnet"] },
  { id: "playbook-zk", type: "playbook", title: "Playbook — On-chain zk verification", description: "Groth16 proofs verified in a Soroban contract via BLS12-381 host functions.", keywords: ["zk", "groth16", "circom", "bls12-381", "playbook", "verifier"], source: "skills/zk-proofs", steps: ["Write the Circom circuit and generate a Groth16 proof", "Build the verifier contract using CAP-59 host functions", "Deploy the verifier and embed its address in the dApp", "Verify proofs on-chain with a fixed public input layout"] },
  { id: "playbook-e2e", type: "playbook", title: "Playbook — E2E a Stellar dApp", description: "Playwright flows wired to Stellar Agentic Kit hooks.", keywords: ["e2e", "playwright", "playbook", "test", "dapp"], source: "tests", steps: ["Run the backend + frontend locally", "Fund a test wallet on testnet", "Drive wallet-connect, contract and payment flows with Playwright", "Assert on-chain effects via the RPC, not just UI state"] },
  { id: "playbook-graph", type: "playbook", title: "Playbook — Work-graph multi-agent build", description: "Plan → fan-out parallel agents per wave → fan-in merge → verify.", keywords: ["work-graph", "agents", "parallel", "playbook", "orchestration", "evals"], source: "CLAUDE.md", steps: ["Decompose the task into node-sized slices owned by single agents", "Order waves: independent nodes parallel, dependents after", "Batch-spawn each wave in one message", "Fan-in merge state deltas, verify against evals, steer on failure"] },

  // ---- Operations (gateway-native) ----
  { id: "op-contract-deploy", type: "operation", title: "Operation — Deploy Soroban contract to testnet", description: "Build + gate + deploy via stellar CLI, record contract ID.", keywords: ["deploy", "operation", "soroban", "testnet", "wasm"], source: "scripts/deploy-contract.sh" },
  { id: "op-rpc-health", type: "operation", title: "Operation — Check Soroban RPC health", description: "POST /getHealth against a Stellar RPC endpoint.", keywords: ["rpc", "health", "operation", "soroban", "monitoring"], source: "packages/forge-gateway/scripts/check-live.mjs" },
  { id: "op-x402-curl", type: "operation", title: "Operation — Curl an x402 endpoint", description: "Expect 402 challenge, then 200 after settlement.", keywords: ["x402", "curl", "operation", "402", "http"], source: "tests/x402-flow.mjs" },
];